- name: find common version
  command: git describe --long
  args:
    chdir: /opt/ansible
  register: common_version_result
  changed_when: false

- name: set common version fact
  set_fact:
    common_version: "{{ common_version_result.stdout }}"

- debug:
    msg: "{{ lookup('fileglob', '/applications/*') }}"

- include_tasks: application.yml
  loop: "{{ lookup('fileglob', '/applications/*') }}"
