- name: find common version
  command: git describe --long
  args:
    chdir: /opt/ansible
  register: common_version_result
  changed_when: false

- name: set common version fact
  set_fact:
    common_version: "{{ common_version_result.stdout }}"

- include_tasks: application.yml
  # would rather use fileglob here but that doesn't work on directories
  loop: "{{ lookup('pipe', 'ls -d /applications/*').splitlines() }}"
