apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ kube_resource_name }}-ansible-cfg"
  namespace: "{{ kube_resource_namespace }}"
data:
  ansible.cfg: |-
    [defaults]
    inventory_plugins = /opt/ansible/plugins/inventory
    stdout_callback = yaml
    callback_whitelist = profile_tasks,timer
    module_utils = /opt/ansible/module_utils
    library = /opt/ansible/library
    inventory = /opt/ansible/inventory,{{ application_operator_applications | map('regex_replace', '^(.*)$', '/applications/\\1/\\1/inventory') | join(',') }}
    filter_plugins = /opt/ansible/plugins/filter
    remote_tmp = /tmp/ansible
    roles_path = /opt/ansible/roles
