apiVersion: v1
kind: Secret
metadata:
  name: application-operator-ssh
  namespace: {{ kube_resource_namespace }}
type: Opaque
data:
  ssh: {{ application_operator_ssh_key | b64encode }}
  known_hosts: {{ application_operator_ssh_known_hosts | b64encode }}
