kube_resource_name: "{{ env }}-application-operator"
kube_resource_namespace: "{{ env }}"
kube_resource_create_namespace: yes
kube_resource_secrets:
  ssh: "{{ lookup('template', kube_resource_template_dir + 'ssh-secrets.yml') | from_yaml }}"
  vault: "{{ lookup('template', kube_resource_template_dir + 'vault-secrets.yml') | from_yaml }}"
kube_resource_configmaps:
  ansible: "{{ lookup('template', kube_resource_template_dir + 'ansible-configmap.yml') | from_yaml }}"

kube_resource_manifest_files: >
  {{ query('fileglob', kube_resource_template_dir + '*manifest.yml') }}

application_operator_repo: "git@github.com:willthames/ansible-operator-test.git"
application_operator_sync_interval: 60
